name: workflow1
on: 
  push:
    branches:
    - main
  schedule:
    - cron: "55 08,20 * * *"
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "hello from gagandeep"
      - name: step2
        run: echo "hello from step2"
      - name: my step 3 for multiple lines 
        run: |
          hostname
          echo "hello from gagandeep"
          sleep 10
          ls -l /
      - run: echo "hello from step 4, A step without any name" 

