name: workflow1
on: 
  push:
    branches:
    - main
  schedule:
    - cron: "55 08,20 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "build started"
          sleep 30
      - name: step2
        run: |
          echo "hello from step2"
          sleep 10
      - name: my step 3 for multiple lines 
        run: |
          hostname
          echo "hello from gagandeep"
          sleep 10
          ls -l /
      - run: echo "build completed" 

  test:
    runs-on: ubuntu-latest
    steps:
      - name: step1 from test
        run: |
          echo "hello from gagandeep"
          sleep 30
      - name: step2 from test
        run: |
          echo "hello from step2"
          sleep 30
